// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Demo configuration for Firebase Emulator

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt3W6PaSy0IHUG4qV3loeVnofIHJo6C4s',
    appId: '1:353191750538:android:7618d2c3f23d70d057b673',
    messagingSenderId: '353191750538',
    projectId: 'demopersistence',
    storageBucket: 'demopersistence.firebasestorage.app',
  );

  // For production, run: flutterfire configure

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkhItKzyAojVpkUqk54qBkwIVO0cmfayo',
    appId: '1:353191750538:ios:9f4c1d47410a81d457b673',
    messagingSenderId: '353191750538',
    projectId: 'demopersistence',
    storageBucket: 'demopersistence.firebasestorage.app',
    iosBundleId: 'ru.yandex.moodTrackerPlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkhItKzyAojVpkUqk54qBkwIVO0cmfayo',
    appId: '1:353191750538:ios:9f4c1d47410a81d457b673',
    messagingSenderId: '353191750538',
    projectId: 'demopersistence',
    storageBucket: 'demopersistence.firebasestorage.app',
    iosBundleId: 'ru.yandex.moodTrackerPlus',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsEoNewMVgaCtBUwUZu0o0IfH5UZEN4Pc',
    appId: '1:353191750538:web:be5dc0df6e46262157b673',
    messagingSenderId: '353191750538',
    projectId: 'demopersistence',
    authDomain: 'demopersistence.firebaseapp.com',
    storageBucket: 'demopersistence.firebasestorage.app',
    measurementId: 'G-BBQKSRN39Z',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsEoNewMVgaCtBUwUZu0o0IfH5UZEN4Pc',
    appId: '1:353191750538:web:8ff5f965f7480fa657b673',
    messagingSenderId: '353191750538',
    projectId: 'demopersistence',
    authDomain: 'demopersistence.firebaseapp.com',
    storageBucket: 'demopersistence.firebasestorage.app',
    measurementId: 'G-9NN69ZSHYR',
  );

}