// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/objectbox/models/mood_entry_box.dart';
import 'models/objectbox/mood_entry_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 4512827764410458830),
    name: 'MoodEntryEntity',
    lastPropertyId: const obx_int.IdUid(10, 4896837405666347529),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6780272814392514137),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3447301921127271822),
        name: 'entryId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4147578345261271153),
        name: 'moodValue',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8099531960537413653),
        name: 'timestamp',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7462357241315233361),
        name: 'note',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6475165492477229539),
        name: 'activities',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5922052533756820258),
        name: 'sleepDurationMinutes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2210975874376881202),
        name: 'sleepTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4470195448590097511),
        name: 'wakeTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 4896837405666347529),
        name: 'photoPath',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 7870224153746433786),
    name: 'MoodEntryBox',
    lastPropertyId: const obx_int.IdUid(10, 738823523226837628),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2717101047766332393),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2867629855762397720),
        name: 'entryId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 7859732748731530789),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6313192582301897381),
        name: 'moodValue',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6087728094826456537),
        name: 'timestamp',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2207808962000358567),
        name: 'note',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7606048750037427185),
        name: 'activities',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7454818240624693235),
        name: 'sleepDurationMinutes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2878264811735369585),
        name: 'sleepTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 73207580496247787),
        name: 'wakeTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 738823523226837628),
        name: 'photoPath',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 7870224153746433786),
    lastIndexId: const obx_int.IdUid(1, 7859732748731530789),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    MoodEntryEntity: obx_int.EntityDefinition<MoodEntryEntity>(
      model: _entities[0],
      toOneRelations: (MoodEntryEntity object) => [],
      toManyRelations: (MoodEntryEntity object) => {},
      getId: (MoodEntryEntity object) => object.id,
      setId: (MoodEntryEntity object, int id) {
        object.id = id;
      },
      objectToFB: (MoodEntryEntity object, fb.Builder fbb) {
        final entryIdOffset = fbb.writeString(object.entryId);
        final noteOffset = object.note == null
            ? null
            : fbb.writeString(object.note!);
        final activitiesOffset = fbb.writeString(object.activities);
        final photoPathOffset = object.photoPath == null
            ? null
            : fbb.writeString(object.photoPath!);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, entryIdOffset);
        fbb.addInt64(2, object.moodValue);
        fbb.addInt64(3, object.timestamp.millisecondsSinceEpoch);
        fbb.addOffset(4, noteOffset);
        fbb.addOffset(5, activitiesOffset);
        fbb.addInt64(6, object.sleepDurationMinutes);
        fbb.addInt64(7, object.sleepTime?.millisecondsSinceEpoch);
        fbb.addInt64(8, object.wakeTime?.millisecondsSinceEpoch);
        fbb.addOffset(9, photoPathOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final sleepTimeValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final wakeTimeValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final entryIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final moodValueParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final timestampParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final noteParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final activitiesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final sleepDurationMinutesParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 16);
        final sleepTimeParam = sleepTimeValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(sleepTimeValue);
        final wakeTimeParam = wakeTimeValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(wakeTimeValue);
        final photoPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final object = MoodEntryEntity(
          id: idParam,
          entryId: entryIdParam,
          moodValue: moodValueParam,
          timestamp: timestampParam,
          note: noteParam,
          activities: activitiesParam,
          sleepDurationMinutes: sleepDurationMinutesParam,
          sleepTime: sleepTimeParam,
          wakeTime: wakeTimeParam,
          photoPath: photoPathParam,
        );

        return object;
      },
    ),
    MoodEntryBox: obx_int.EntityDefinition<MoodEntryBox>(
      model: _entities[1],
      toOneRelations: (MoodEntryBox object) => [],
      toManyRelations: (MoodEntryBox object) => {},
      getId: (MoodEntryBox object) => object.id,
      setId: (MoodEntryBox object, int id) {
        object.id = id;
      },
      objectToFB: (MoodEntryBox object, fb.Builder fbb) {
        final entryIdOffset = fbb.writeString(object.entryId);
        final noteOffset = object.note == null
            ? null
            : fbb.writeString(object.note!);
        final activitiesOffset = fbb.writeString(object.activities);
        final photoPathOffset = object.photoPath == null
            ? null
            : fbb.writeString(object.photoPath!);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, entryIdOffset);
        fbb.addInt64(2, object.moodValue);
        fbb.addInt64(3, object.timestamp.millisecondsSinceEpoch);
        fbb.addOffset(4, noteOffset);
        fbb.addOffset(5, activitiesOffset);
        fbb.addInt64(6, object.sleepDurationMinutes);
        fbb.addInt64(7, object.sleepTime?.millisecondsSinceEpoch);
        fbb.addInt64(8, object.wakeTime?.millisecondsSinceEpoch);
        fbb.addOffset(9, photoPathOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final sleepTimeValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final wakeTimeValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final entryIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final moodValueParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final timestampParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final noteParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final activitiesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final sleepDurationMinutesParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 16);
        final sleepTimeParam = sleepTimeValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(sleepTimeValue);
        final wakeTimeParam = wakeTimeValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(wakeTimeValue);
        final photoPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final object = MoodEntryBox(
          id: idParam,
          entryId: entryIdParam,
          moodValue: moodValueParam,
          timestamp: timestampParam,
          note: noteParam,
          activities: activitiesParam,
          sleepDurationMinutes: sleepDurationMinutesParam,
          sleepTime: sleepTimeParam,
          wakeTime: wakeTimeParam,
          photoPath: photoPathParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [MoodEntryEntity] entity fields to define ObjectBox queries.
class MoodEntryEntity_ {
  /// See [MoodEntryEntity.id].
  static final id = obx.QueryIntegerProperty<MoodEntryEntity>(
    _entities[0].properties[0],
  );

  /// See [MoodEntryEntity.entryId].
  static final entryId = obx.QueryStringProperty<MoodEntryEntity>(
    _entities[0].properties[1],
  );

  /// See [MoodEntryEntity.moodValue].
  static final moodValue = obx.QueryIntegerProperty<MoodEntryEntity>(
    _entities[0].properties[2],
  );

  /// See [MoodEntryEntity.timestamp].
  static final timestamp = obx.QueryDateProperty<MoodEntryEntity>(
    _entities[0].properties[3],
  );

  /// See [MoodEntryEntity.note].
  static final note = obx.QueryStringProperty<MoodEntryEntity>(
    _entities[0].properties[4],
  );

  /// See [MoodEntryEntity.activities].
  static final activities = obx.QueryStringProperty<MoodEntryEntity>(
    _entities[0].properties[5],
  );

  /// See [MoodEntryEntity.sleepDurationMinutes].
  static final sleepDurationMinutes = obx.QueryIntegerProperty<MoodEntryEntity>(
    _entities[0].properties[6],
  );

  /// See [MoodEntryEntity.sleepTime].
  static final sleepTime = obx.QueryDateProperty<MoodEntryEntity>(
    _entities[0].properties[7],
  );

  /// See [MoodEntryEntity.wakeTime].
  static final wakeTime = obx.QueryDateProperty<MoodEntryEntity>(
    _entities[0].properties[8],
  );

  /// See [MoodEntryEntity.photoPath].
  static final photoPath = obx.QueryStringProperty<MoodEntryEntity>(
    _entities[0].properties[9],
  );
}

/// [MoodEntryBox] entity fields to define ObjectBox queries.
class MoodEntryBox_ {
  /// See [MoodEntryBox.id].
  static final id = obx.QueryIntegerProperty<MoodEntryBox>(
    _entities[1].properties[0],
  );

  /// See [MoodEntryBox.entryId].
  static final entryId = obx.QueryStringProperty<MoodEntryBox>(
    _entities[1].properties[1],
  );

  /// See [MoodEntryBox.moodValue].
  static final moodValue = obx.QueryIntegerProperty<MoodEntryBox>(
    _entities[1].properties[2],
  );

  /// See [MoodEntryBox.timestamp].
  static final timestamp = obx.QueryDateProperty<MoodEntryBox>(
    _entities[1].properties[3],
  );

  /// See [MoodEntryBox.note].
  static final note = obx.QueryStringProperty<MoodEntryBox>(
    _entities[1].properties[4],
  );

  /// See [MoodEntryBox.activities].
  static final activities = obx.QueryStringProperty<MoodEntryBox>(
    _entities[1].properties[5],
  );

  /// See [MoodEntryBox.sleepDurationMinutes].
  static final sleepDurationMinutes = obx.QueryIntegerProperty<MoodEntryBox>(
    _entities[1].properties[6],
  );

  /// See [MoodEntryBox.sleepTime].
  static final sleepTime = obx.QueryDateProperty<MoodEntryBox>(
    _entities[1].properties[7],
  );

  /// See [MoodEntryBox.wakeTime].
  static final wakeTime = obx.QueryDateProperty<MoodEntryBox>(
    _entities[1].properties[8],
  );

  /// See [MoodEntryBox.photoPath].
  static final photoPath = obx.QueryStringProperty<MoodEntryBox>(
    _entities[1].properties[9],
  );
}
